version: '3.8'
services:
  mongodb-challenge:
    image: mongo:4.4.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Joabesv
      - MONGO_INITDB_ROOT_PASSWORD=challenge-password
      - MONGO_INITDB_DATABASE=challenge-db
    volumes:
      - mongodb-data:/var/lib/mongodb/data/
    ports:
      - '27017:27017'

volumes:
  mongodb-data: